ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ com.vacancy.server.ApplicationKt.module ]
    }
    security {
        jwt {
            secret = "mySecretKey123"
            issuer = "vacancy-server"
            audience = "vacancy-app"
            expiration = 86400000
        }
    }
    database {
        url = "jdbc:postgresql://localhost:5433/vacancy_db?sslmode=disable"
        driver = "org.postgresql.Driver"
        user = "vacancy_user"
        password = "pass123"
    }
}